version: '3.8'

services:
  stt_service:
    container_name: stt_service_container
    build: ./src/backend/stt_service
    ports:
      - "82:82"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  ocr_service:
    container_name: ocr_service_container
    build: ./src/backend/ocr_service
    ports:
      - "81:81"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]

  video2text_service: 
    container_name: video2text_container
    build: ./src/backend/v2t_service
    ports:
      - "85:85"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    volumes:
      - ./models:/code/models

  encoder_service:
    container_name: encoder_container
    build: ./src/backend/encoder_service
    ports:
      - "8666:8666"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    volumes:
      - ./faiss_index:/code/app/faiss_index
      - ./models:/code/models

  db:
    container_name: db_container
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  server: 
    container_name: server_container
    build: ./src/backend/server
    depends_on:
      - db
      - stt_service
      - ocr_service
      - video2text_service
      - encoder_service
    ports:
      - "8910:8910" 
volumes:
  postgres-db: