version: '2.1'

services:
  asr_service:
    container_name: asr_service_container
    build: ./src/ASR
    restart: always

  ocr_service:
    container_name: ocr_service_container
    build: ./src/OCR
    restart: always