version: '3.8'

services:
  server_service: 
    build:
      context: ./src/backend/server
    ports:
      - "8667:8667"  
    volumes:
      - ./src/backend/server/cmd:/app
    command: go run cmd/main.go

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: