version: '2.1'

services:
  stt_service:
    container_name: stt_service_container
    build: ./src/backend/stt_service
    restart: always
    ports:
      - "80:80"

  ocr_service:
    container_name: ocr_service_container
    build: ./src/backend/ocr_service
    restart: always
    ports:
      - "81:81"