version: '3.8'

services:
  server: 
    build: ./src/backend/server
    ports:
      - "8667:8667"  
    volumes:
      - .:/usr/src/app
    command: go run src/backend/server/cmd/main.go

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: