version: '2.1'

services:
  stt_service:
    container_name: stt_service_container
    build: ./src/backend/stt_service
    restart: always
    ports:
      - "80:80"

  ocr_service:
    container_name: ocr_service_container
    build: ./src/backend/ocr_service
    restart: always
    ports:
      - "81:81"

  video2text_service:
    container_name: video2text_container
    build: ./src/backend/v2t_service
    ports:
      - "85:85"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  encoder_service:
    container_name: encoder_container
    build: ./src/backend/encoder_service
    ports:
      - "86:86"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility